#!/usr/bin/env python
"""
DwcaInfo return the InstitutionCode and CollectionCode of the first record of darwincore archive zipfile generated by gbif.org

"""

__title__ = 'DwcaInfo'
__author__ = 'Arturo Vargas <avargas@inbio.ac.cr>'


import sys
import zipfile
import lxml.etree as etree

class DwcaInfo:
    """Contain InstitutionCode, CollectionCode and datasetTitle"""

    def __init__(self):
        self.institutionCode = '' 
        self.collectionCode  = ''
        self.datasetTitle    = ''

    def __getInstitutionCollection(self, file):
        """find institutionCode and collectionCode"""
        # header line
        line = file.readline()
        line = line.split('\t')
        institutionIndex = line.index('institutionCode')
        collectionIndex  = line.index('collectionCode')
    
        # first data line
        line = file.readline()
        line = line.split('\t')
        self.institutionCode = line[institutionIndex]
        self.collectionCode  = line[collectionIndex]
        return self

    def __getDatasetTitle(self, file):
        """ find datasetTitle inside xml file """
        tree = etree.parse(file)
        root = tree.getroot()
        datasetTitle = root.find('dataset').find('title')
        self.datasetTitle = datasetTitle.text
        return datasetTitle.text

    @classmethod
    def getDwcaInfo(cls, fileName):
        """Giving a Dwc-a zip file return DwcaInfo object"""
        zip = zipfile.ZipFile(fileName)
        file = zip.open('occurrence.txt')
    
        dwcaInfo = cls()

        cls.__getInstitutionCollection(dwcaInfo, file)
    
        # find datasetTitle, assume one dataset in the file
        datasetFilename = ''
        for name in zip.namelist():
            if name.startswith('dataset/'): 
                datasetFilename = name
                break
    
        file = zip.open(datasetFilename)
        cls.__getDatasetTitle(dwcaInfo, file)
    
        return dwcaInfo

# main code in case call came from command line
if __name__ == "__main__":
    try:
        fileName = sys.argv[1]

        dwcaInfo = DwcaInfo.getDwcaInfo(fileName)
        print 'institution %s collection %s\ndataset: %s' % ( 
                                dwcaInfo.institutionCode, 
                                dwcaInfo.collectionCode,
                                dwcaInfo.datasetTitle)

    except IndexError:
        print "usage: %s dwc-a_zip_file\n" % sys.argv[0]
